apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: ping
spec:
  displayName: "Ping"
  description: "A Ping Kamelet"
  parameters:
    - name: message
      description: The message to generate
      schema:
        type: string
  flow:
    from:
      uri: timer:tick
      steps:
        - set-body:
            constant: "Hello [here there'll be the message] !!!"
        - to: "log:info"
