apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamelets
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kamelets
  template:
    metadata:
      labels:
        name: kamelets
    spec:
      serviceAccountName: kamelets
      containers:
        - name: kamelets
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - kamelets
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kamelets"
